
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 02 13:27:45 CST 2013
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 80;
  public static final int OPERADOR_ASIGNAR_IZQUIERDA = 77;
  public static final int REAL = 39;
  public static final int NUMERO_FLOTANTE_CIENTIFICO = 85;
  public static final int OPERADOR_MIEMBRO_PUNTERO = 70;
  public static final int PACKED = 37;
  public static final int TYPE = 13;
  public static final int READ = 38;
  public static final int CONST = 19;
  public static final int OPERADOR_COMPARACION_DIFERENTE = 71;
  public static final int OPERADOR_ARITMETICO_IGUAL = 61;
  public static final int OPERADOR_OTRO_ASSIGNMENT = 69;
  public static final int UNTIL = 47;
  public static final int NUMERO_ENTERO = 82;
  public static final int OPERADOR_PARENTESIS_ABRE = 57;
  public static final int OPERADOR_OTRO_PUNTO_Y_COMA = 55;
  public static final int FALSE = 23;
  public static final int NOT = 36;
  public static final int NIL = 35;
  public static final int ARRAY = 3;
  public static final int ERROR = 84;
  public static final int VAR = 14;
  public static final int INLINE = 30;
  public static final int OPERADOR_COMPARACION_Y_RELACION_MAYOR = 63;
  public static final int THEN = 12;
  public static final int GOTO = 28;
  public static final int RECORD = 40;
  public static final int MOD = 34;
  public static final int OPERADOR_ARITMETICO_RESTA = 53;
  public static final int OPERADOR_OTRO_DOS_PUNTOS = 68;
  public static final int OPERADOR_ARITMETICO_DIVISION = 54;
  public static final int WRITE = 49;
  public static final int TRUE = 46;
  public static final int OPERADOR_ARITMETICO_INCREMENTAR_IGUAL = 72;
  public static final int OPERADOR_ARITMETICO_MULTIPLICAR_IGUAL = 74;
  public static final int WHILE = 48;
  public static final int CHAR = 18;
  public static final int BOOLEAN = 15;
  public static final int LONGINT = 33;
  public static final int SHORTINT = 43;
  public static final int DO = 21;
  public static final int FOR = 25;
  public static final int OPERADOR_OTRO_COMA = 56;
  public static final int DIV = 20;
  public static final int DOWNTO = 22;
  public static final int ELSE = 5;
  public static final int PROCEDURE = 11;
  public static final int INT = 31;
  public static final int EOF = 0;
  public static final int FUNCTION = 27;
  public static final int OPERADOR_ASIGNAR_DERECHA = 76;
  public static final int OPERADOR_ARITMETICO_INCREMENTAR = 66;
  public static final int OPERADOR_ASIGNAR_IZQUIERDA_IGUAL = 78;
  public static final int CARACTER = 83;
  public static final int REPEAT = 41;
  public static final int LABEL = 32;
  public static final int OPERADOR_ARITMETICO_SUMA = 52;
  public static final int OPERADOR_ARITMETICO_DIVIDIR_IGUAL = 75;
  public static final int NUMERO_FLOTANTE = 81;
  public static final int IN = 29;
  public static final int OR = 9;
  public static final int SET = 42;
  public static final int OPERADOR_COMPARACION_Y_RELACION_MENOR_IGUAL_EQ = 64;
  public static final int error = 1;
  public static final int OPERADOR_ARITMETICO_DECREMENTAR_IGUAL = 73;
  public static final int OPERADOR_COMPARACION_Y_RELACION_MENOR = 62;
  public static final int IF = 7;
  public static final int OPERADOR_PARENTESIS_CIERRA = 58;
  public static final int OF = 8;
  public static final int END = 6;
  public static final int OPERADOR_PARENTESIS_CUADRADO_ABRE = 59;
  public static final int FILE = 24;
  public static final int OPERADOR_ASIGNAR_DERECHA_IGUAL = 79;
  public static final int OPERADOR_COMPARACION_Y_RELACION_MAYOR_IGUAL = 65;
  public static final int BEGIN = 4;
  public static final int CASE = 17;
  public static final int FORWARD = 26;
  public static final int STRING = 44;
  public static final int PROGRAM = 10;
  public static final int BYTE = 16;
  public static final int AND = 2;
  public static final int OPERADOR_ARITMETICO_DECREMENTAR = 67;
  public static final int TO = 45;
  public static final int OPERADOR_ARITMETICO_MULTIPLICACION = 51;
  public static final int XOR = 50;
  public static final int OPERADOR_PARENTESIS_CUADRADO_CIERRA = 60;
}

